# Generated by Django 5.0.4 on 2024-04-11 10:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_apikey_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='added',
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='views',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
