# Generated by Django 5.0.4 on 2024-04-11 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_log_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='news',
        ),
    ]
